### ISSUE TITLE
Column `quote` in CSV export format is empty

### ISSUE THREAD

**Issue by stefanherzog** [judell/facet#4]
Hi Jon! Thanks a lot for the awesome hypothes.is tools you created!

I encountered what I believe to be a bug, but maybe I'm simply misunderstanding something. In the latter case, I'd be eager understand things correctly.

**If I export an annotation, the column `quote` in CSV export format is empty (the column `text` is populated as expected), whereas the annotated/quoted text does appear in the JSON version (in the field `exact`) and on the HTML version.**

As a minimal reproducible example I exported the most recent public annotation on `https://www.nytimes.com/*` and attached the three outputs (zipped into [`hypothesis_export.zip`](https://github.com/judell/facet/files/4434466/hypothesis_export.zip)as github doesn't seem to allow me to upload those file types).

Thanks!

**Comment by judell** [comment]
Yep, that's a bug, will fix, thanks for the heads-up.

**Comment by stefanherzog** [comment]
Thanks a lot!

**Comment by judell** [comment]
Fixed by https://github.com/judell/hlib/commit/fe82f09930bb30b592be06f3f8086344741d88fc
