### ISSUE TITLE
partial tag search not working?

### ISSUE THREAD

**Issue by tgbugs** [judell/facet#5]
I seem to remember that it was possible to search using tag prefixes, but it doesn't seem to be working anymore, https://jonudell.info/h/facet/?max=1000&tag=RRID&group=world.

**Comment by judell** [comment]
Not for the tag field, you can do this however:

https://jonudell.info/h/facet/?max=1000&group=world&user=scibot&any=RRID

Does that help?

**Comment by tgbugs** [comment]
Ok, I must have misremembered. Unfortunately the RRIDs are only added as tags so this wont find them. Thanks!
