### ISSUE TITLE
"Title" column missing in CSV format

### ISSUE THREAD

**Issue by jessedepagter** [judell/facet#6]
Hi Jon,

Let me start by saying that the facet tool is absolutely awesome! I have been experimenting a lot with it already, analyzing my annotations. 

Small question: in the CSV format, the column "Title" is missing, whereas in in the JSON export it is there. Since it is sometimes more comfortable to work with a CSV export, I would like to ask if there is a specific reason for its absence? Or maybe I am making a mistake? For me this column is very useful because I mainly annotate PDF files and the title is a very fast and intuitive way of identifying in which PDF file specific annotations are located. 

All the best,

Jesse

**Comment by judell** [comment]
Thanks for the heads-up, that was just an oversight, I'll add the title to the CSV.

**Comment by jessedepagter** [comment]
ok, thank you!
