### ISSUE TITLE
Can't access private group

### ISSUE THREAD

**Issue by vanbang9710** [judell/facet#7]
I filled in user, API token but couldn't change to private group. Refreshing doesn't work.
![image](https://user-images.githubusercontent.com/52906188/215450070-06586b1a-e24b-4f1a-959f-59d8f8b98498.png)

**Comment by judell** [comment]
It looks like you are authenticated. Can you use the group dropdown to select a private group?

**Comment by vanbang9710** [comment]
No. I can only see All and Public

**Comment by judell** [comment]
Hmm, sorry, I'm a bit stumped. 

You don't need the usename, that's only for search not authentication, the token alone provides authentication. 

Have you used this token elsewhere successfully?

All I can think of now is:

- try a different browser

- regenerate the token (if you're not depending on it to be valid elsewhere)

Sorry! If you do figure it out please let me know.

**Comment by vanbang9710** [comment]
Thank you. I regenerated the token and it works now.

**Comment by judell** [comment]
I'm puzzled as to how this happened. The tokens do not expire, I've been using mine for years. But glad to know you're unblocked.
